<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2017.0.2.363
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Amorous - Wedding Muse Template Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => '',
		'to' => ''
	),
	'fields' => array(
		'custom_U414' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'FULL NAME',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'FULL NAME\' is required.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'EMAIL ADDRESS',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'EMAIL ADDRESS\' is required.',
				'format' => 'Field \'EMAIL ADDRESS\' has an invalid email.'
			)
		),
		'custom_U408' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'COMMENTS',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U419' => array(
			'order' => 3,
			'type' => 'checkbox',
			'label' => 'Butternut squash ravioli with mascarpone cream sauce and roasted vegetables (V)',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Butternut squash ravioli with mascarpone cream sauce and roasted vegetables (V)\' is required.'
			)
		),
		'custom_U496' => array(
			'order' => 4,
			'type' => 'checkbox',
			'label' => 'Chicken breast stuffed with butternut squash and brie, mashed sweet potatoes, and roasted vegetables',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Chicken breast stuffed with butternut squash and brie, mashed sweet potatoes, and roasted vegetables\' is required.'
			)
		),
		'custom_U3333' => array(
			'order' => 5,
			'type' => 'checkbox',
			'label' => 'Braised short ribs with cranberry and shallot au jus with mashed potatoes and roasted vegetables',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Braised short ribs with cranberry and shallot au jus with mashed potatoes and roasted vegetables\' is required.'
			)
		),
		'custom_U3345' => array(
			'order' => 6,
			'type' => 'checkbox',
			'label' => 'Children\'s Meal',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Children\'s Meal\' is required.'
			)
		)
	)
);

process_form($form);
?>
